### ISSUE TITLE
[FEATURE] A reproducible environment

### ISSUE THREAD

**Issue by wjs20** [brennanaba/ImmuneBuilder#16]
Hi 

The documentation on creating a working environment for this tool reproducibility is a bit confusing, and I am having trouble getting it to work. 

Your first instruction is to install immunebuilder using pip, which will install torch because it is listed as a requirement in the setup script. Then you say pytorch is required and link to the official pytorch install instructions, but at this clashes with the install triggered by the setup script. 

Also I have installed pdbfixer as instructed but, ABodyBuilder2 seems unable to import it as a module. 

Maybe you could provide an environment.yml and requirements.txt files for the stuff that can't be installed with conda. I think typically its best practice to install what you can in your conda environment and then install additional packages via pip.

**Comment by brennanaba** [comment]
Hi William,

You are right in that the installation instructions could be clearer. I have changed them a bit to make it easier to follow.

I will look into adding an environment.yml file at some in the future, but feel free to submit a pull request!!!

The pdbfixer issue may be because the version of pip you used to install ImmuneBuilder was not the one in your conda environment. You can check if this is the case by doing `which pip`.

All the best,

Brennan

**Comment by wjs20** [comment]
Hi Brennan

You were correct about pdbfixer, my conda env was active but my python interpreter was from some other virtualenv I hadn't deactivated. Isn't python package management fun...

Thanks for updating the install instructions. IMO they are much easier to follow now. 

I think maybe adding an environment.yml might be tricky actually, because the environment will depend on which version of CUDA you have installed. I think the instructions as they are now are sufficiently clear. 

Will close this now.
