### ISSUE TITLE
Sequence checks missing residue threshold

### ISSUE THREAD

**Issue by msilva00** [brennanaba/ImmuneBuilder#23]
Hi,
Thanks for making ImmuneBuilder available. For ABodyBuilder2 I tend to get failures for sequences not passing the `number_single_sequence` check. Specifically, too many missing residues. 

Specific line for the error is within `ImmuneBuilder.sequence_checks.number_single_sequence`:

```
    # Check for missing residues assuming imgt numbering
    assert (max(numbers) > 120) and (min(numbers) < 8), f"Sequence missing too many residues to model correctly. Please give whole sequence:\n{sequence}"
```

**Question:** What is the motivation for this? That missing residues at the tails of the sequence have to be minimized? The assertion statement implies that there is a threshold to how many missing residues are allowed for this.

# Code to reproduce
This is the case where both heavy and light chains fail the sequence check under the assertion  `(max(numbers)>20)`
```
from ImmuneBuilder import ABodyBuilder2
predictor = ABodyBuilder2()

output_file = "my_antibody.pdb"
sequences = {
  'H': 'QVQLVESGGGMVQPGEVPETLLCSLDSPSVAMAAGSARLQGKGLEWVSVISYEEGRKYYADSVKGRFTISRDNSKNTLYLQMSSLRAEDTAVYYCAEDSEQGWFGDPWGALTSGARDNGHRLS',
  'L': 'DIVLTQTPGTLSLSPGERATLSCRASQSVSSYLAWYQQKPGQAPRLLIYDASNRATGIPARFSGSGSGTDFTLTISRLEPEDFAVYYCQQYGSSPLTFGRRDQGWRS'}

antibody = predictor.predict(sequences)
antibody.save(output_file)
```

To access the specific error: 
```
from ImmuneBuilder.sequence_checks import number_single_sequence
number_single_sequence(sequence='QVQLVESGGGMVQPGEVPETLLCSLDSPSVAMAAGSARLQGKGLEWVSVISYEEGRKYYADSVKGRFTISRDNSKNTLYLQMSSLRAEDTAVYYCAEDSEQGWFGDPWGALTSGARDNGHRLS',chain="H")
number_single_sequence(sequence='DIVLTQTPGTLSLSPGERATLSCRASQSVSSYLAWYQQKPGQAPRLLIYDASNRATGIPARFSGSGSGTDFTLTISRLEPEDFAVYYCQQYGSSPLTFGRRDQGWRS', chain="L")

```

Specifically `max(numbers) == 120` for both the heavy and light chains. What are the consequences of adjusting the cutoff?

**Comment by brennanaba** [comment]
Hi Mary,

The sequence length checks were added because all structures seen by the Immunebuilder models during training were not missing more residues than that. You can try disabling them and the model should still run, but I can not guarantee that the predicted structure will be accurate. 

An alternative to this, that is more likely to generate accurate structures, would be to fill in the missing residues in your Fv sequence. This can be done either by assuming they are germline or by using a language model such as Ablang https://github.com/oxpig/AbLang
You would only have to do this for the sequences were the assertion is raised.

I hope that helps!!


All the best,


Brennan
