### ISSUE TITLE
Questions regarding Immunebuilder accuracy of prediction

### ISSUE THREAD

**Issue by imunick** [brennanaba/ImmuneBuilder#29]
I have a few specific questions regarding the accuracy of prediction section of your paper, and I would be extremely grateful if you could provide some clarification.​

Firstly, I noticed that the paper mentions the use of Cβ instead of O when calculating the RMSD, predominantly involving the backbone. I am curious as to why you chose to disregard the oxygen atoms and pick the Cβ sidechain atom and I would really like to know the reason behind this approach.​

Secondly, I am curious about the methodology used for aligning the two structures (crystal versus predicted) in your study. Could you please elaborate on whether this alignment was based on heavy atom/backbone alignment or if it involved Cα+C+N+Cβ, similar to the RMSD approach?​

I would also like to ask you for your choice of alignment, where you mention that you chose to align on the corresponding chain and then calculate the CDRs RMSD. To my understanding, chain H of the predicted structure was aligned with chain H of the crystal structure and then the CDRs-H1-3 were calculated, and then the same logic was applied for chain L. If that is the case, what was the reason behind this alignment, in contrary to the conventional whole-structure alignment? Does it penalize the angle between the heavy and light chain way less, if it is not predicted that well?​

Moreover, I would like to ask about the software or method you used to align and calculate the RMSD for these structures. Most of the literature utilizes PyMOL, which I have also used, but I am interested in determining if different results are produced using another software or method.​

Finally, regarding the RMSPE, you are mentioning that a low predicted error does not necessarily indicate an accurate structure. The example and the graph you are providing with the CDR-H3 does indeed show that, but, considering the complexity of this region, I would like to know whether the same correlation is being seen in the rest CDR loops, which are easier to predict.​

I look forward to your response and would like to thank you in advance for your time and consideration.

**Comment by brennanaba** [comment]
Hi imunick,

That is a lot of questions!! 😅

1. I chose those atoms because they are all part of the same rigid group. If you want to redo the benchmark including O, feel free to do so. I suspect it won't change the results much.
2. Structures were aligned based on Cα+C+N+Cβ atoms.
3. This type of alignment is the conventional approach for antibodies. It does, by design, not penalize the angle between the heavy and light chain. This is to separate the models ability at predicting CDR loops and VH-VL orientation (which is compared in the "Heavy and light chain packing" section)
4. I used the Kabsch algorithm. I do not agree that the majority of the literature uses PyMol for this type of calculations, although I think in this case the results should be similar.
5. I would expect that if you see a very high RMSPE for another CDR loop it would also be likely to have a large error. I haven't seen many cases of this though. 

Hope that helps!!

All the best,

Brennan
